# Generated by Django 2.2.6 on 2019-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauron', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceltemplate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exceltemplate',
            name='title',
        ),
        migrations.AddField(
            model_name='exceltemplate',
            name='file',
            field=models.FileField(default='', upload_to='excel_template'),
        ),
        migrations.AddField(
            model_name='exceltemplate',
            name='file_name',
            field=models.CharField(default='unnamed', max_length=100, verbose_name='Excel file name'),
        ),
    ]
