# Generated by Django 2.2.6 on 2019-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauron', '0002_auto_20191023_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=100, verbose_name='File name')),
                ('file', models.FileField(default='', upload_to='files')),
            ],
        ),
        migrations.DeleteModel(
            name='ExcelTemplate',
        ),
    ]
