# Generated by Django 2.2.6 on 2019-10-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauron', '0003_auto_20191023_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='unnamed', max_length=100, verbose_name='File name')),
                ('file', models.FileField(default='', upload_to='files')),
            ],
        ),
        migrations.RenameModel(
            old_name='File',
            new_name='DonwloadFileModel',
        ),
        migrations.RenameField(
            model_name='donwloadfilemodel',
            old_name='name',
            new_name='title',
        ),
    ]
